apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
    # Each container (CPU and Memory)
    - type: Container
      min:
        cpu: "50m"
        memory: "128Mi"
      max:
        cpu: "1"
        memory: "2Gi"
      defaultRequest:
        cpu: "50m"
        memory: "128Mi"
      default:
        cpu: "100m"
        memory: "256Mi"

    # Storage PVC
    - type: PersistentVolumeClaim
      min:
        storage: "1Gi"
      max:
        storage: "10Gi"
